### ISSUE TITLE
Embedded links don't work

### ISSUE THREAD

**Issue by PierceVDR** [techcodeshq/astrius-issues#2]
# Describe the bug
When previewing my course description, the embedded link for \[replit](replit.com) doesn't bring me to replit.com. It brings me to [https://www.astrius.app/courses/cl5wo8sb6059109kw3j1w1u5i/replit.com](https://www.astrius.app/courses/cl5wo8sb6059109kw3j1w1u5i/replit.com), which is an error 404 page.

# To Reproduce
1. Click "+ Create a Course"
2. In the description include \[replit](replit.com)
3. Click "Preview"
4. Click on the embedded link

# Expected behavior
Would bring me to [replit.com](replit.com)

# Screenshots
![image](https://user-images.githubusercontent.com/109817568/180486855-fb4a64d3-6294-465d-8407-34c54a81782c.png)
![image](https://user-images.githubusercontent.com/109817568/180487002-5a05f79b-9292-44a2-97c4-7b06a3b8b10b.png)
![image](https://user-images.githubusercontent.com/109817568/180487083-2f5d8ef4-4cf5-4cef-8db3-65703e10c75a.png)

# Additional context
\---

**Comment by giilbert** [comment]
Hi Pierce,

the link you write in the parenthesis must be a absolute link (like `https://replit.com`).  Right now you’re are using a relative link, which will bring you a webpage relative to the current’s.
