### ISSUE TITLE
Comments and Output read as code

### ISSUE THREAD

**Issue by TJ-Hacker** [techcodeshq/astrius-issues#3]
# Describe the bug
When writing executable code blocks in the markdown editor, Python's comments are displayed as code. So keywords like "is" or "function" are highlighted in different colors, which could confuse readers by directing their attention to the wrong places. Quotes are also treated as if they note Strings, so they highlight entire lines of code and just mess up the code highlights too.

The same bug applies to the Output section of the code blocks. The entire output is read as code too.

# To Reproduce
1. Just go to any markdown editor and create an executable code block.
2. Create a comment and type out a normal English sentence, or use some quotes.
3. Optional: You can also add a print statement using quotes, such as "Hi, my name is TJ and I'm a rising senior."
4. Look at the preview of the document.
5. Scroll down to the executable code preview. (If you're also testing the print statement, run the code).
6. You should be able to see what I'm talking about.

# Expected behavior
Comments should be greyed out completely, and the Output shouldn't be read as code.
Keywords and quotes shouldn't affect the formatting of the text (colors shouldn't be used to highlight them).

# Screenshots
![bugReport](https://user-images.githubusercontent.com/55298280/180804081-bcbc0157-4ee2-41da-9421-7635eaa7bf2c.png)

**Comment by iDarkLightning** [comment]
I believe this is fixed with the recent change, let me know
