### ISSUE TITLE
Hitting "Run" a second time doesn't stop any code that's running

### ISSUE THREAD

**Issue by PierceVDR** [techcodeshq/astrius-issues#4]
# Describe the bug
Hitting "Run" a second time doesn't stop any code that's running in challenges.

# To Reproduce
See video.

# Expected behavior
Spamming the run button would restart the program, and stop any currently running code

# Video (Open in a new tab to make it look less like monochrome plaid)
![too much clickity doesn't stop more outputty](https://i.imgur.com/WqMfPyG.gif)

**Comment by giilbert** [comment]
Fixed in `a9758f40ae1727da94a83e2b5497becf627ea294`
