### ISSUE TITLE
Issue in challenges expected output

### ISSUE THREAD

**Issue by kavyamanchanda** [techcodeshq/astrius-issues#6]
# Describe the bug
When I enter a new expected input/output pair, I press enter to correspond each line to a new print statement in the output. But, when I run my code and get the exact same output, it doesn't pass the testing because the system considers all outputs in a single line. 

# Expected behavior
I think my code should pass the testing because my output is the same. I think each new line should be considered a new print statement and checked separately.

# Screenshots
![Screenshot (124)](https://user-images.githubusercontent.com/96886826/180985418-9186329c-bc82-475c-a8f2-6ea3fbcd2177.png)

**Comment by giilbert** [comment]
Fixed in `a9758f40ae1727da94a83e2b5497becf627ea294`
